#! /bin/sh

sxhkd &
pkill xterm

bspc monitor -d I II III IV V VI VII VIII IX X XI

bspc config border_width        1 
bspc config window_gap          4

#bspc config right_padding	277

bspc config split_ratio          4
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#009900
bspc config active_border_color \#0000b3

bspc desktop --focus ^11 && /usr/bin/start-bspwm-utils2 &

start-bspwm-utils --debian
compton -b
conky &
